-- SQL Script: Calculate Total Revenue Generated by Each Store in January 2023

-- Objective:
-- Calculate the total revenue generated by each store in January 2023.

SELECT
    store_id,                           -- The identifier for the store
    store_location,                     -- The location of the store
    SUM(transaction_qty * unit_price) AS total_revenue -- Calculates total revenue (quantity * unit price) for each store
FROM
    coffee_shop_sales                   -- Specifies the table 'coffee_shop_sales' as requested
WHERE
    transaction_date BETWEEN '2023-01-01' AND '2023-01-31' -- Filters transactions for January 2023
GROUP BY
    store_id,                           -- Groups the results by store ID
    store_location;                     -- Further groups by store location